
version: '{build}'
os: Visual Studio 2015
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: WAjoRKctIoxjPZQ2Pj2P2ek9XPEeoRKjDTMf+2A3t/EKbYWEbLY1HmrYAu8fpE4k
install:
- ps: >-
    nuget update -self

    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"

    & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-preview2-003121" -InstallDir "$env:DOTNET_INSTALL_DIR"

    dotnet restore

    nuget restore packages.config -PackagesDirectory packages
    
    dotnet build .\src\PaulMiami.AspNetCore.Authentication.Authenticator\project.json
build: off
test_script:
- ps: ./Coverage.ps1